#!/usr/bin/env bash

if [ $@ == "setup" ]; then
	git init --bare $HOME/.dotfiles/
	git --git-dir=$HOME/.dotfiles --work-tree=$HOME --local config status.showUntrackedFiles no
else
	git --git-dir=$HOME/.dotfiles --work-tree=$HOME $@
fi
